#!/usr/bin/env bash

set -euo pipefail

if command -v podman &>/dev/null
then
    container_manager='podman'
else
    container_manager='docker'
fi

image='gparse-dev'

mydir="$(dirname "$0")/"
cd "$mydir"

"$container_manager" build --tag="$image" .
"$container_manager" run --interactive --tty "$image" "$@"
