---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gparse-dev-dpl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gparse-dev
  replicas: 2
  template:
    metadata:
      name: gparse-dev-pod
      labels:
        app.kubernetes.io/name: gparse-dev
    spec:
      containers:
        - name: gparse-dev
          image: gparse-dev
          imagePullPolicy: Never
          command:
            - morbo
            - src/gparse.pl
          ports:
            - name: gparse-pod-port
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gparse-dev-svc
spec:
  selector:
    app.kubernetes.io/name: gparse-dev
  ports:
    - name: gparse-svc-port
      port: 3000
      targetPort: gparse-pod-port
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gparse-dev-pdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gparse-dev
  minAvailable: 1
---
