---
apiVersion: v1
kind: Pod
metadata:
  name: gparse-dev-pod
  labels:
    app.kubernetes.io/name: gparse-dev
spec:
  containers:
    - name: gparse-dev
      image: gparse-dev
      imagePullPolicy: Never
      command:
        - morbo
        - src/gparse.pl
      ports:
        - name: gparse-pod-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gparse-dev-svc
spec:
  selector:
    app.kubernetes.io/name: gparse-dev
  ports:
    - name: gparse-svc-port
      port: 3000
      targetPort: gparse-pod-port
---
